version: "3.9"

services:
  ollama:
    build: .
    container_name: alice-ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - OLLAMA_MODELS=/models
      - OLLAMA_USE_CUDA=1
    volumes:
      - ./models:/models
    ports:
      - "11434:11434"
    restart: unless-stopped
