#!/bin/bash
# ============================================================
# PROJ-85: Seed the entity-less timer intents into Weaviate HAIntent
# ============================================================
# alice-ha-sync generates HAIntent objects from alice.ha_intent_templates,
# but only for entities it fetches from Home Assistant. The timer intents
# (domain 'timer') have no HA entity, so they are never generated by the
# sync and would be wiped by a force-all resync if they were.
#
# This script reads the timer templates straight from PostgreSQL and writes
# one HAIntent object per pattern into Weaviate:
#   - entityId  : ""          (no HA entity)
#   - domain    : "timer"      (the marker ha_path.decide_path routes on)
#   - service   : "timer.<intent>"
#   - intentTemplate : "timer:<intent>"
#
# It first deletes every existing domain=timer HAIntent object so a re-run
# is idempotent. Safe to run any number of times.
#
# Usage:
#   ./seed-timer-intents.sh [WEAVIATE_URL] [POSTGRES_CONTAINER]
#   ./seed-timer-intents.sh http://weaviate:8080 postgres
# ============================================================
set -euo pipefail

WEAVIATE_URL="${1:-http://weaviate:8080}"
PG_CONTAINER="${2:-postgres}"
PG_USER="${POSTGRES_USER:-user}"
PG_DB="${POSTGRES_DB:-alice}"
CERTAINTY_THRESHOLD="${CERTAINTY_THRESHOLD:-0.82}"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'

echo "============================================================"
echo "PROJ-85: Seed timer intents into Weaviate HAIntent"
echo "============================================================"
echo "Weaviate:  ${WEAVIATE_URL}"
echo "Postgres:  ${PG_CONTAINER} (${PG_USER}/${PG_DB})"
echo ""

command -v jq >/dev/null || { echo -e "${RED}jq is required${NC}"; exit 1; }

# 1. Pull the timer templates as JSON: [{intent, service, patterns:[...]}]
echo -n "Reading timer templates from PostgreSQL... "
TEMPLATES_JSON=$(docker exec -i "${PG_CONTAINER}" psql -U "${PG_USER}" -d "${PG_DB}" -tAc \
  "SELECT COALESCE(json_agg(json_build_object('intent', intent, 'service', service, 'patterns', patterns)), '[]'::json)
   FROM alice.ha_intent_templates
   WHERE domain = 'timer' AND is_active = TRUE AND language = 'de';")

COUNT=$(echo "$TEMPLATES_JSON" | jq 'length')
if [ "$COUNT" -eq 0 ]; then
  echo -e "${RED}none found — run migration 069 first${NC}"
  exit 1
fi
echo -e "${GREEN}${COUNT} template(s)${NC}"

# 2. Delete existing domain=timer objects (idempotent re-run).
echo -n "Deleting existing domain=timer HAIntent objects... "
DEL_CODE=$(curl -s -o /tmp/timer_del.json -w "%{http_code}" -X DELETE \
  -H "Content-Type: application/json" \
  -d '{"match":{"class":"HAIntent","where":{"path":["domain"],"operator":"Equal","valueText":"timer"}}}' \
  "${WEAVIATE_URL}/v1/batch/objects")
if [[ "$DEL_CODE" == 2* ]]; then
  echo -e "${GREEN}OK${NC} ($(jq -r '.results.matches // 0' /tmp/timer_del.json 2>/dev/null || echo 0) removed)"
else
  echo -e "${YELLOW}HTTP ${DEL_CODE} (continuing)${NC}"
fi

# 3. Build + insert one object per pattern.
echo "Inserting timer utterances..."
INSERTED=0
FAILED=0
while read -r row; do
  INTENT=$(echo "$row" | jq -r '.intent')
  SERVICE=$(echo "$row" | jq -r '.service')
  while read -r pattern; do
    [ -z "$pattern" ] && continue
    # These patterns are the vectorised text — a leftover {value}/{name}
    # placeholder would poison the embedding (see PROJ-85 QA BUG-9).
    case "$pattern" in
      *"{"*)
        echo -e "  ${RED}SKIP${NC} placeholder in pattern: ${pattern}"
        FAILED=$((FAILED+1))
        continue
        ;;
    esac
    BODY=$(jq -n \
      --arg u "$pattern" \
      --arg s "$SERVICE" \
      --arg it "timer:${INTENT}" \
      --argjson ct "$CERTAINTY_THRESHOLD" \
      '{class:"HAIntent", properties:{
          utterance:$u, entityId:"", domain:"timer", service:$s,
          parameters:"{}", language:"de", intentTemplate:$it, certaintyThreshold:$ct
      }}')
    CODE=$(curl -s -o /tmp/timer_ins.json -w "%{http_code}" -X POST \
      -H "Content-Type: application/json" -d "$BODY" \
      "${WEAVIATE_URL}/v1/objects")
    if [[ "$CODE" == 2* ]]; then
      INSERTED=$((INSERTED+1))
    else
      FAILED=$((FAILED+1))
      echo -e "  ${RED}FAIL${NC} (${CODE}) ${pattern}"
      cat /tmp/timer_ins.json 2>/dev/null && echo ""
    fi
  done < <(echo "$row" | jq -r '.patterns[]')
done < <(echo "$TEMPLATES_JSON" | jq -c '.[]')

echo ""
echo "------------------------------------------------------------"
echo -e "  Inserted: ${GREEN}${INSERTED}${NC}  Failed: ${RED}${FAILED}${NC}"
echo "------------------------------------------------------------"
[ "$FAILED" -eq 0 ] && echo -e "${GREEN}Timer intents seeded.${NC}" && exit 0
echo -e "${RED}Finished with errors.${NC}" && exit 1
